writing the read me file for the project
GSG-CF05/FinanceApp_Team7 pull request #26
Opened 2022-02-08 09:25 UTC by mariamabunada

relate #25

2022-02-08 09:33 UTC, mohmmed23 approved these changes, later dismissed

2022-02-08 10:01 UTC, AjShatalii approved these changes, later dismissed

2022-02-08 13:05 UTC, sara219 requested changes
you created this pull request to add the readme file, and you push other files not related to the purpose of the brunch

**delete anything not related to this branch**

2022-02-08 14:22 UTC, mohmmed23 submitted a review, later dismissed

2022-02-08 14:36 UTC, AjShatalii submitted a review, later dismissed

2022-02-08 21:47 UTC, muhannaAtalla20 submitted a review, later dismissed

2022-02-09 09:08 UTC, AjShatalii approved these changes

2022-02-09 10:58 UTC, sara219 approved these changes

2022-02-09 15:15 UTC, mohmmed23 approved these changes

2022-02-09 15:16 UTC, muhannaAtalla20 approved these changes

2022-02-09 15:16 UTC, merged